//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24h Volume.
        /// </summary>
        internal static string _24hVolume {
            get {
                return ResourceManager.GetString("24hVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change (24h).
        /// </summary>
        internal static string Change_24h_ {
            get {
                return ResourceManager.GetString("Change(24h)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulating Supply.
        /// </summary>
        internal static string CirculatingSupply {
            get {
                return ResourceManager.GetString("CirculatingSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulating Supply:.
        /// </summary>
        internal static string CirculatingSupply_ {
            get {
                return ResourceManager.GetString("CirculatingSupply:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoinInfo.
        /// </summary>
        internal static string CoinInfo {
            get {
                return ResourceManager.GetString("CoinInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price.
        /// </summary>
        internal static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Price:.
        /// </summary>
        internal static string CurrentPrice_ {
            get {
                return ResourceManager.GetString("CurrentPrice:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Market.
        /// </summary>
        internal static string GoToMarket {
            get {
                return ResourceManager.GetString("GoToMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Coin Repo.
        /// </summary>
        internal static string GototheCoin_Repo {
            get {
                return ResourceManager.GetString("GototheCoin Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the HomePage .
        /// </summary>
        internal static string GototheHomePage {
            get {
                return ResourceManager.GetString("GototheHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        internal static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap.
        /// </summary>
        internal static string MarketCap {
            get {
                return ResourceManager.GetString("MarketCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Cap:.
        /// </summary>
        internal static string MarketCap_ {
            get {
                return ResourceManager.GetString("MarketCap:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markets:.
        /// </summary>
        internal static string Markets {
            get {
                return ResourceManager.GetString("Markets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSupply:.
        /// </summary>
        internal static string Max_Supply_ {
            get {
                return ResourceManager.GetString("Max Supply:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        internal static string Moreinfo {
            get {
                return ResourceManager.GetString("Moreinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Top Currencies :.
        /// </summary>
        internal static string NumberOfTopCurrencies__ {
            get {
                return ResourceManager.GetString("NumberOfTopCurrencies :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Change (24h):.
        /// </summary>
        internal static string PriceChange__24h__ {
            get {
                return ResourceManager.GetString("PriceChange (24h):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Change Percentage (24h):.
        /// </summary>
        internal static string PriceChangePercentage_24h__ {
            get {
                return ResourceManager.GetString("PriceChangePercentage(24h):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_ {
            get {
                return ResourceManager.GetString("Theme:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Dark/Light Theme.
        /// </summary>
        internal static string ToggleDark_LightTheme {
            get {
                return ResourceManager.GetString("ToggleDark/LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Coins.
        /// </summary>
        internal static string TopCoins {
            get {
                return ResourceManager.GetString("TopCoins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Supply:.
        /// </summary>
        internal static string TotalSupply_ {
            get {
                return ResourceManager.GetString("TotalSupply:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Volume:.
        /// </summary>
        internal static string TotalVolume_ {
            get {
                return ResourceManager.GetString("TotalVolume:", resourceCulture);
            }
        }
    }
}
